{% set version = "1.8.1" %}

package:
  name: jsoncpp
  version: {{ version }}

source:
  fn: jsoncpp-{{ version }}.tar.gz
  url: https://github.com/open-source-parsers/jsoncpp/archive/{{ version }}.tar.gz
  sha256: 858db2faf348f89fdf1062bd3e79256772e897e7f17df73e0624edf004f2f9ac

build:
  number: 0
  string: 0_flyem
  skip: true  # [(win and not py27)]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    - toolchain
    - cmake
    - pkg-config  # [unix]
    - python

test:
  requires:
    - python 2.7.*  # [win and py27]
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]

  commands:
    # Verify headers are present.
    - test -d "${PREFIX}/include/json"           # [unix]

    # Verify pkg-config file is present.
    - test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"  # [unix]

    # Verify libraries are present.
    - test -f "${PREFIX}/lib/libjsoncpp.a"          # [unix]
    - test -f "${PREFIX}/lib/libjsoncpp.so"         # [linux]
    - test -f "${PREFIX}/lib/libjsoncpp.dylib"      # [osx]

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: Public Domain/MIT
  summary: A C++ library for interacting with JSON.

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
