{% set version = "1.6.2" %}

package:
  name: jsoncpp
  version: {{ version }}

source:
  fn: jsoncpp-{{ version }}.tar.gz
  url: https://github.com/open-source-parsers/jsoncpp/archive/{{ version }}.tar.gz

build:
  number: 5

requirements:
  build:
    - toolchain
    - cmake
    - pkg-config  # [unix]
    - python 2.7*

test:
  commands:
    # Verify headers are present.
    - test -f "${PREFIX}/include/json/json.h"      # [unix]

    # Verify pkg-config file is present.
    - test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"  # [unix]

    # Verify libraries are present.
    - test -f "${PREFIX}/lib/libjsoncpp.a"          # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libjsoncpp${SHLIB_EXT}']"  # [unix]

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: Public Domain/MIT
  license_file: LICENSE
  summary: A C++ library for interacting with JSON.

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
